-- Core schema (PRD)
CREATE TABLE public.planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE,
  preco_mensal DECIMAL(10, 2) NOT NULL DEFAULT 0,
  max_usuarios INTEGER NOT NULL DEFAULT 1,
  max_agentes INTEGER NOT NULL DEFAULT 1,
  limite_mensagens_mes INTEGER NOT NULL DEFAULT 100,
  stripe_price_id TEXT UNIQUE,
  features JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  cor TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER planos_set_updated_at
  BEFORE UPDATE ON public.planos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  plano_id BIGINT NOT NULL REFERENCES public.planos (id),
  chave_api_llm TEXT,
  contexto_ia JSONB NOT NULL DEFAULT '{}'::jsonb,
  stripe_customer_id TEXT UNIQUE,
  email TEXT,
  telefone TEXT,
  endereco TEXT,
  status TEXT NOT NULL DEFAULT 'ativa',
  data_adesao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  proxima_cobranca TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_empresas_plano_id ON public.empresas (plano_id);

CREATE TRIGGER empresas_set_updated_at
  BEFORE UPDATE ON public.empresas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.perfis (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas (id) ON DELETE CASCADE,
  role public.app_role NOT NULL DEFAULT 'user',
  email TEXT NOT NULL,
  nome_completo TEXT,
  telefone TEXT,
  cargo TEXT,
  status TEXT NOT NULL DEFAULT 'ativo',
  ultimo_acesso TIMESTAMPTZ,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_perfis_empresa_id ON public.perfis (empresa_id);
CREATE INDEX idx_perfis_role ON public.perfis (role);

CREATE TRIGGER perfis_set_updated_at
  BEFORE UPDATE ON public.perfis
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.agentes_ia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas (id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  instrucoes TEXT NOT NULL DEFAULT '',
  icone_url TEXT,
  descricao TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_popular BOOLEAN NOT NULL DEFAULT false,
  cor TEXT,
  created_by UUID REFERENCES public.perfis (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agentes_ia_empresa_id ON public.agentes_ia (empresa_id);

CREATE TRIGGER agentes_ia_set_updated_at
  BEFORE UPDATE ON public.agentes_ia
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.conversas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  empresa_id BIGINT NOT NULL REFERENCES public.empresas (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.perfis (id) ON DELETE CASCADE,
  agente_id BIGINT REFERENCES public.agentes_ia (id) ON DELETE SET NULL,
  mensagens JSONB NOT NULL DEFAULT '[]'::jsonb,
  titulo TEXT,
  tokens_usados INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ativa',
  contexto_atual JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_conversas_empresa_id ON public.conversas (empresa_id);
CREATE INDEX idx_conversas_user_id ON public.conversas (user_id);

CREATE TRIGGER conversas_set_updated_at
  BEFORE UPDATE ON public.conversas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.uso_recursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas (id) ON DELETE CASCADE,
  mes_referencia DATE NOT NULL,
  mensagens_enviadas INTEGER NOT NULL DEFAULT 0,
  tokens_consumidos INTEGER NOT NULL DEFAULT 0,
  agentes_ativos INTEGER NOT NULL DEFAULT 0,
  usuarios_ativos INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (empresa_id, mes_referencia)
);

CREATE INDEX idx_uso_recursos_empresa_id ON public.uso_recursos (empresa_id);

CREATE TRIGGER uso_recursos_set_updated_at
  BEFORE UPDATE ON public.uso_recursos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.perfis (id) ON DELETE SET NULL,
  acao TEXT NOT NULL,
  entidade_tipo TEXT NOT NULL,
  entidade_id BIGINT,
  empresa_id BIGINT REFERENCES public.empresas (id) ON DELETE SET NULL,
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_auditoria_empresa_id ON public.auditoria (empresa_id);
CREATE INDEX idx_auditoria_user_id ON public.auditoria (user_id);
